# Generated by Django 2.0.13 on 2020-05-03 00:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.FileField(upload_to='uploads/index/')),
                ('page', models.CharField(choices=[('index', 'Index'), ('about', 'About'), ('service', 'Service'), ('contact', 'Contact')], max_length=20)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'adek_banner',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Language')),
            ],
            options={
                'db_table': 'adek_contact',
                'ordering': ('id',),
            },
        ),
    ]
